name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - { name: '3.10', python: '3.10', os: ubuntu-latest, tox: py310, mongodb: '4.4'}
          - { name: '3.9', python: '3.9', os: ubuntu-latest, tox: py39, mongodb: '4.4'}
          - { name: '3.8', python: '3.8', os: ubuntu-latest, tox: py38, mongodb: '4.4'}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb }}
      - name: Install dependencies
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade virtualenv tox tox-gh-actions
      - name: Start mongo ${{ matrix.mongodb-version }}
        run: |
          mongo eve_test --eval 'db.createUser({user:"test_user", pwd:"test_pw", roles:["readWrite"]});'
      - name: Run tox targets for ${{ matrix.python }}
        run: tox -e ${{ matrix.tox }}
